<img src="escuela_economia_una_logo.png" width="260" height="60">
<center>
    <b>Econometría</b><br>
    <b>Profesor:  Alexander Amoretti</b><br>
    <b>Desarrollo:  Diego Armando Barquero Sánchez, Estudiante de Tercer Ciclo</b>
<br><br>   
<div style="font-size:200%;color:white; background-color: #630b57;">Aplicación del Método de MCO provando Retornos Constantes de Escala en Costa Rica</div>
<div style="font-size:100%;color:white; background-color: #630b57;">Empleando tanto los valores reales como en su Variación Natural</div>

<i>Creado:     2023-Ago-16 
    <br>
    Actualizado: ------ </i>

## Librerías

In [80]:
import pandas as pd #librería para manipulación de datos
import numpy as np #Librería para operaciones matemáticas
import matplotlib #librería para graficar
from matplotlib import pyplot as plt #librería para graficar
import statsmodels.api as sm #librería para análisis estadístico
from IPython.display import Image # Para imagénes
from statsmodels.formula.api import ols # Para pruebas de hipotesis
import warnings
warnings.filterwarnings('ignore')

## Cargamos los datos

In [81]:
datos = pd.read_excel("PIB empleo FBKF trimestral.xlsx")

## Observamos las cinco primeras filas del dataframe

In [82]:
datos.head(5)

   Trimestre    Empleo           PIB          FBKF
0  IIIT 2010  1881.514  6.485904e+06  1.203865e+06
1   IVT 2010  1886.234  6.796036e+06  1.219068e+06
2    IT 2011  1802.040  6.830432e+06  1.091437e+06
3   IIT 2011  1765.039  6.754869e+06  1.142741e+06
4  IIIT 2011  1836.662  6.736463e+06  1.239719e+06

In [83]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Trimestre  52 non-null     object
 1   Empleo     52 non-null     float64
 2   PIB        52 non-null     float64
 3   FBKF       52 non-null     float64
dtypes: float64(3), object(1)
memory usage: 1.8+ KB

# $$ln(PIB) = \beta_1 +  \beta_2 ln(Empleo) + \beta_3 ln(FBKF) + \varepsilon_i$$

### **La forma funcional de la Cobb Douglas emplea logaritmos naturales en donde en este caso particular asignamos las variables de la siguiente forma**

$$PIB = Q(K,L) = Función  de  producción$$

$$Empleo = L = Trabajo$$


$$FBKF = K = Capital$$

## Primeramente utilizamos la librería numpy para crear nuevas columnas que contengan a las variables pero con logaritmo natural

In [90]:
datos["LPIB"] = np.log(datos["PIB"])
datos["LEmpleo"] = np.log(datos["Empleo"])
datos["LFBKF"] = np.log(datos["FBKF"])
datos.head()

,Trimestre,Empleo,PIB,FBKF,LPIB,LEmpleo,LFBKF
0,IIIT 2010,1881.514,6.485904e+06,1.203865e+06,15.685142,7.539832,14.001048
1,IVT 2010,1886.234,6.796036e+06,1.219068e+06,15.731850,7.542338,14.013597
2,IT 2011,1802.040,6.830432e+06,1.091437e+06,15.736898,7.496675,13.903006
3,IIT 2011,1765.039,6.754869e+06,1.142741e+06,15.725774,7.475928,13.948940
4,IIIT 2011,1836.662,6.736463e+06,1.239719e+06,15.723046,7.515705,14.030395

##  Asignamos aquellas variables explicatorias y dependientes

In [91]:

Y = datos["LPIB"]
X = datos[["LEmpleo", "LFBKF"]]
X = sm.add_constant(X) # procimental para la constante ( B1  )
#
X # Las observamos

    const   LEmpleo      LFBKF
0     1.0  7.539832  14.001048
1     1.0  7.542338  14.013597
2     1.0  7.496675  13.903006
3     1.0  7.475928  13.948940
4     1.0  7.515705  14.030395
5     1.0  7.559095  14.102067
6     1.0  7.598123  14.028428
7     1.0  7.585070  14.017953
8     1.0  7.600014  14.136451
9     1.0  7.597981  14.136309
10    1.0  7.591198  14.017510
11    1.0  7.605096  14.036528
12    1.0  7.614183  14.211185
13    1.0  7.644097  14.230402
14    1.0  7.642145  14.092995
15    1.0  7.624624  14.081096
16    1.0  7.633273  14.203072
17    1.0  7.630267  14.276948
18    1.0  7.626184  14.103420
19    1.0  7.643657  14.195849
20    1.0  7.631973  14.292228
21    1.0  7.614568  14.206054
22    1.0  7.597266  14.101839
23    1.0  7.578021  14.201442
24    1.0  7.586868  14.309989
25    1.0  7.632094  14.400991
26    1.0  7.630829  14.225373
27    1.0  7.640046  14.258993
28    1.0  7.634681  14.180897
29    1.0  7.598720  14.367729
30    1.0  7.603255  14.198872
31    1.0  7.677880  14.301738
32    1.0  7.667692  14.273376
33    1.0  7.680325  14.328027
34    1.0  7.683296  14.135618
35    1.0  7.688545  14.161088
36    1.0  7.679072  14.160651
37    1.0  7.688372  14.299995
38    1.0  7.699922  14.058515
39    1.0  7.464657  14.153248
40    1.0  7.520835  14.172935
41    1.0  7.577199  14.236049
42    1.0  7.597072  14.041354
43    1.0  7.585465  14.286031
44    1.0  7.646663  14.290301
45    1.0  7.651578  14.394394
46    1.0  7.650681  14.253299
47    1.0  7.675076  14.230888
48    1.0  7.690690  14.197883
49    1.0  7.683892  14.384130
50    1.0  7.648789  14.278298
51    1.0  7.659930  14.322263

## Corremos el modelo como tal empleando MCO

In [92]:
modelo = sm.OLS(Y,X).fit()
print(modelo.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   LPIB   R-squared:                       0.602
Model:                            OLS   Adj. R-squared:                  0.586
Method:                 Least Squares   F-statistic:                     37.10
Date:                Thu, 17 Aug 2023   Prob (F-statistic):           1.55e-10
Time:                        01:50:11   Log-Likelihood:                 61.345
No. Observations:                  52   AIC:                            -116.7
Df Residuals:                      49   BIC:                            -110.8
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.7038      1.567      1.726      0.091      -0.445       5.853
LEmpleo        0.8053      0.227      3.547      0.001       0.349       1.262
LFBKF          0.4996      0.106      4.710      0.000       0.286       0.713
==============================================================================
Omnibus:                        1.407   Durbin-Watson:                   0.594
Prob(Omnibus):                  0.495   Jarque-Bera (JB):                1.210
Skew:                           0.193   Prob(JB):                        0.546
Kurtosis:                       2.360   Cond. No.                     2.39e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.39e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

## Probar la existencia de rendimientos constantes de escala

### En el contexto de una función de producción Cobb-Douglas, la hipótesis rendimientos constante de escala implica que la suma de los coeficientes de las variables de entrada (alpha y beta) debe ser igual a 1. Esto indica que si duplica las entradas, la salida será proporcional a 1, también el doble, confirmando los rendimientos constantes a escala.
### $$Q=K^αL^β$$
### $$Rendimientos Constantes de Escala = α + β = 1 = β1In(Empleo) + β2In(FBKF)$$
- Donde β1 y β2 son los coeficientes de las variables de entrada Empleo y FBKF, respectivamente.

### Combinación lineal de coeficientes: en un modelo de regresión lineal, los coeficientes representan el cambio en la variable dependiente para un cambio de una unidad en la variable predictora correspondiente. La hipótesis Rendimientos Constantes de Escala establece que la suma de estos coeficientes debe ser igual a 1.
#### -Una de las representaciones matriciales existentes de la restricción anteriormente discutida es :
### $$[β1, β2] X [Empleo, FBKF]^T = 1$$
#### - Ahora si incluimos todos los coeficientes ( β0, β1, β2 ), constante y pendientes
### [1] $$[0, 1, 1] X [β0, β1, β2]^T = 1$$
### [2] $$0β0 + 1β1 + 1β2 = 1$$

#### - Prueba de Wald: La prueba de Wald es una prueba de hipótesis que evalúa si se cumple un conjunto de restricciones lineales sobre los coeficientes del modelo. La prueba compara la diferencia entre los modelos sin restricciones y restringidos y determina si las restricciones son estadísticamente significativas.

#### - Al especificar la matriz de restricción [0, 1, 1] en la prueba de Wald, esencialmente está probando si la suma de los coeficientes de Empleo y FBKF en el modelo de regresión múltiple es igual a 1. Si el valor p de la prueba de Wald es menor que un nivel de significación elegido (p. ej., 0,05), rechazaría la hipótesis nula y concluiría que los coeficientes no suman 1, lo que indica una desviación de los rendimientos constantes a escala.

In [93]:
restricción_matricial = np.array([[0, 1, 1]])

### Establecemos las Hipótesis Nula y Alternativa

### $$[H0] : α + β = 1$$
### $$[H1] : α + β ≠  1$$

#### - Realizamos el wald test como tal

In [111]:
wald_test = modelo.wald_test(restricción_matricial)
print("Wald Test Results:")
print(wald_test)

Wald Test Results:
<F test: F=array([[46.14299631]]), p=1.3890012007557596e-08, df_denom=49, df_num=1>

###  Ergo existe una desviación de los rendimientos constantes de escala tanto que el p-value es menor que 0.05 , se descarta la H0 y se acepta la H1